### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by ibidani** [xetdata/xet-tools#15]
**Is your feature request related to a problem? Please describe.**
compatibility with Windows client could help handle many other professionals who rely on windows exclusive software such as Autocad

**Describe the solution you'd like**
Windows git xet client

**Comment by ylow** [comment]
A windows client is in development and on its way!

**Comment by rajatarya** [comment]
@ibidani Circling back on this - we are starting to test our Windows implementation. What version of Windows are you using? We have been primarily thinking about Windows 11 - would that work for you?

**Comment by erinys** [comment]
git-xet for Windows is now available with v0.8.0. Follow [our installation instructions](https://xethub.com/assets/docs/getting-started/installation) to try it out!
