### ISSUE TITLE
Inconsistent progress bar on uploads

### ISSUE THREAD

**Issue by erinys** [xetdata/xet-tools#2]
**Describe the bug**
The upload progress bar has issues, sometimes it doesn’t show up (on a subsequent push in the same repo, like I make a new repo, push some stuff, then push a second commit and no progress bar, but I do see network activity), sometimes it also gets stuck.

**Frequency**
Intermittent

**Steps to reproduce**
N/A

**Expected behavior**
Consistent upload progress bar showing each time there is a push.

**Screenshots**
N/A

**Environment**
 - Internet connection: Wired fiber
 - Device: Linux box
 - CLI version: xet-v0.1.0

**Additional context**
Via email feedback from Antoine.

**Comment by port8080** [comment]
Agniv: 

Using `git bash`, I haven't been able to repro this.

**Comment by erinys** [comment]
Resolved with the release of v0.5.0.
