### ISSUE TITLE
`git xet mount` fails, then inaccurately claims success, on Manjaro

### ISSUE THREAD

**Issue by zorbathut** [xetdata/xet-tools#25]
**Describe the bug**
`git xet mount` does not seem to work on Manjaro; confusingly, it *claims* it worked, but it didn't.

**Frequency**
Persistent.

**Steps to reproduce**
1. Install Manjaro
2. Install `git-xet`
3. Attempt to mount a repo
4. Observe that you got an empty directory instead

**Expected behavior**
Ideally, mounting a repo should work! But at the very least, mounting a repo shouldn't say it was successful if it wasn't successful.

**Screenshots**
Slightly sanitized terminal copy-paste:
```
    ~/werk/xettest  git xet mount https://xethub.com/zorbathut/testgit.git                                                         ✔ 
Mounting to "/home/zorba/werk/xettest/testgit"
Cloning into temporary directory "/tmp/.tmpUe61oI"
Username for 'https://xethub.com': zorba
Password for 'https://zorba@xethub.com': 
Mounting as a background task...
Setting up mount point...
0 bytes in 2 objects mounted
mount.nfs: failed to apply fstab options

Mount at "/home/zorba/werk/xettest/testgit" successful. Unmount with 'umount "/home/zorba/werk/xettest/testgit"'
Mount complete in 9.032182s
    ~/werk/xettest  cd testgit                                                                                              ✔  9s  
    ~/werk/xettest/testgit  ls -al                                                                                                 ✔ 
total 8
drwxr-xr-x 2 zorba zorba 4096 Apr  6 07:46 .
drwxr-xr-x 3 zorba zorba 4096 Apr  6 07:46 ..
    ~/werk/xettest/testgit                                
```

**Environment**
OS, Manjaro. I suspect nothing else here is relevant.

**Additional context**
I assume there's some configuration detail that Xethub doesn't like; this is about 20% "it failed" and about 80% "it claimed it succeeded when it actually failed".

**Comment by ylow** [comment]
Hi! Thanks for trying git-xet!  We have not tested on Manjaro. I think it might be related to the `mount.nfs: failed to apply fstab options`. A couple of questions:

1. Which version of git-xet are you running?
2. Can you make sure you have nfs-utils package installed? We depend on having the NFS client.

We will also investigate on our side. Thanks!

**Comment by zorbathut** [comment]
> Which version of git-xet are you running?

gitxet 0.9.0-118801da

> Can you make sure you have nfs-utils package installed? We depend on having the NFS client.

Apparently I do! Happy to do other tests, for the record :)

**Comment by ylow** [comment]
"0 bytes in 2 objects mounted" is also rather suspicious.  I suspect it actually mounted (you can check run `mount` and see.), but its somehow just empty.

A few more questions. Thanks a lot for your help!!!

1: What is your git version?
2: It is possible that the repo did not actually clone:
Check in `/tmp/.tmpUe61o` (in your log above) and see if there are files in there:
We depend on `git clone --mirror`. Can you see if this works?
```
git clone --mirror https://xethub.com/zorbathut/testgit.git
```
3: `XET_LOG_LEVEL=debug git xet mount ... ` will print lots of diagnostic stuff. You can email it to me `ylow@xethub.com`

Thanks!!

**Comment by zorbathut** [comment]
> I suspect it actually mounted (you can check run mount and see.), but its somehow just empty.

Doesn't show up in the mount list, I'm afraid (I'm grepping for the directory name).

> 1: What is your git version?

2.40.0

> Check in /tmp/.tmpUe61o (in your log above) and see if there are files in there:

Well, that directory doesn't exist, but re-attempting a mount makes a new directory show up, with a `repo` directory that contains the `.git` d.

> We depend on git clone --mirror. Can you see if this works?

Yup, seems to work fine (assuming we expect it to generate the internal .git structure.)

> 3: XET_LOG_LEVEL=debug git xet mount ...  will print lots of diagnostic stuff. You can email it to me ylow@xethub.com

Will do!

**Comment by ylow** [comment]
The root issue seems to be that we are not correctly checking for failure of the mount command. We should automatically retry with "sudo mount.nfs", but that did not happen.

**Comment by ylow** [comment]
We have release an updated linux binary https://github.com/xetdata/xet-tools/releases/tag/v0.9.0 !
Please let us know if this works!

**Comment by zorbathut** [comment]
Yup, that solves it. Thank you!
