### ISSUE TITLE
No .pkg for v0.10.1 on Mac

### ISSUE THREAD

**Issue by charlesfrye** [xetdata/xet-tools#27]
**Describe the bug**
The [v0.10.1 release](https://github.com/xetdata/xet-tools/releases/tag/v0.10.1) does not include a .pkg, so many installation paths fail.

**Frequency**
Persistent.

**Steps to reproduce**
To reproduce the behavior:
1. Go to [this install page](https://xethub.com/explore/install) or [this install page](https://xethub.com/assets/docs/getting-started/installation)
2. Follow recommended instructions for Mac OS X installation, clicking [this link](https://github.com/xetdata/xet-tools/releases/download/v0.10.1/xet-mac-universal.pkg) or [this link](https://github.com/xetdata/xet-tools/releases/latest/download/xet-mac-universal.pkg).
3. See a 404.
or, I think this is related:
1. `brew tap xetdata/xet-tools && brew install xet-tools` on OS X.
2. See error:
```sh
Error: xet-tools: SHA256 mismatch
Expected: 39b9827a385cebd62f181309ca4f88cd44cf8675884593b71c427397f72cac08
  Actual: bbffd5e168051cef15bc89ebe812a81bfb8c8562a7758ceb0c0e9fe4f84a8588
```

**Expected behavior**
xet-tools to install

**Environment**
 - Device: MacBook Pro
 - OS: Ventura 13.1
 - zsh

**Comment by seanses** [comment]
Thanks for catching the problem! This installation issue has been fixed. Both installation path (through MacOS pkg and through MacOS Homebrew) are working now.
