### ISSUE TITLE
Commit history display

### ISSUE THREAD

**Issue by sneheshs** [xetdata/xet-tools#30]
**Is your feature request related to a problem? Please describe.**
As you can see in the commit history, while it is useful to see the commit list with the hash, it is meaningless from the user interface standpoint. It would be much cleaner to be able to see the commit comments.
<img width="300" alt="image" src="https://github.com/xetdata/xet-tools/assets/5719055/36322147-ea18-4571-b233-d91448904362">

**Describe the solution you'd like**
Display commit comments (and/ or other commit summary eg number of file etc. space permitting) instead. The link could take to the same commit and hovering on the link would show the commit hash anyway so we would get both.

**Describe alternatives you've considered**
Click on the link, wait for a commit page to load then read the message, back button, click on the other commit link and repeat.

**Comment by erinys** [comment]
Would showing the first X characters of the commit message be a good solution for this?

**Comment by Kelton8Z** [comment]
And have a ellipsis to expand into full message with newlines potentially

**Comment by sneheshs** [comment]
Yeah that's a good idea to fit in the limited space. Basically only have the author icon and the first few characters of the commit message with ellipsis at the end.

[author icon] this is the first few ...

And when hover the line show full commit message as a tooltip along with the age of the commit or anything else that's relevant. When clicked goes to the commit link.

**Comment by erinys** [comment]
Internally tracked in https://github.com/xetdata/xethub/issues/3996.

**Comment by allisonwhilden** [comment]
We have shipped an update to the commit history display. Check it out when you get a chance and let us know if it doesn't address this feedback. Thank you!

**Comment by sneheshs** [comment]
Absolutely LOVE LOVE LOVE the new commit history!!! Thank you so much! Great job!

**Comment by allisonwhilden** [comment]
So happy to hear that. Thank you so much!
