### ISSUE TITLE
Confusing Commit Graph

### ISSUE THREAD

**Issue by sneheshs** [xetdata/xet-tools#31]
Please pardon my ignorance perhaps. Please see screenshot. I have no idea what this graph means.

![image](https://uploads.linear.app/04f79090-88ee-4279-886c-d14ec911b7eb/5c326f7a-d522-421a-baaf-54d480c816ce/3f26e2b9-6a69-4c89-8923-2c3410e0ed32?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA0Zjc5MDkwLTg4ZWUtNDI3OS04ODZjLWQxNGVjOTExYjdlYi81YzMyNmY3YS1kNTIyLTQyMWEtYmFhZi01NGQ0ODBjODE2Y2UvM2YyNmUyYjktNmE2OS00Yzg5LTg5MjMtMmMzNDEwZTBlZDMyIiwiaWF0IjoxNzA5NzcwNzIxLCJleHAiOjMzMjgwMzMwNzIxfQ.C1lokLwudFQud03L0oF2dKmjsBFo6-13ZkOZy4Vp-LI "=1122x")

Typically I see a git graph something like this where I can see the notes flow and commit messages and it makes sense. And these are typically what the developers committed with the commit message they wrote. I am not sure what this commit graph is showing.

![image](https://uploads.linear.app/04f79090-88ee-4279-886c-d14ec911b7eb/934faca4-2973-4f3e-920d-a10b0eda6f15/f0435410-9e35-422e-b9d3-0bb5edd10cf4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA0Zjc5MDkwLTg4ZWUtNDI3OS04ODZjLWQxNGVjOTExYjdlYi85MzRmYWNhNC0yOTczLTRmM2UtOTIwZC1hMTBiMGVkYTZmMTUvZjA0MzU0MTAtOWUzNS00MjJlLWI5ZDMtMGJiNWVkZDEwY2Y0IiwiaWF0IjoxNzA5NzcwNzIxLCJleHAiOjMzMjgwMzMwNzIxfQ.NGcT-QNpgiKDfPrtDo3K-9r8pmkfkJvUULAlBbGkSsU "=1122x")

**Comment by erinys** [comment]
Internal work tracked in https://github.com/xetdata/xethub/issues/3996.
