### ISSUE TITLE
Multiple Unknown File types summary

### ISSUE THREAD

**Issue by sneheshs** [xetdata/xet-tools#36]
**Is your feature request related to a problem? Please describe.**
The File types summary has a whole bunch of "Unknown" types. Having multiple categories of "unknown" doesn't make sense, nor does it add any value to seeing them without context.

**Describe the solution you'd like**
Option 1) the file extension used to determine the unknown could also be shown like so Unknown (.mmr) or as a tooltip.
Option 2) have a single "Unknown" category with all the extensions like so Unknown (.mmr, .abc, ...) and more in the tooltip or just all of them in the tooltip. I'm sure there are many other ideas that could make this better.

**Describe alternatives you've considered**
See solution

**Additional context**

![image](https://uploads.linear.app/04f79090-88ee-4279-886c-d14ec911b7eb/cb9eea9f-156a-459b-80b1-0026d39ee9df/4e224630-5993-499a-91b9-5e0cbc345d36?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA0Zjc5MDkwLTg4ZWUtNDI3OS04ODZjLWQxNGVjOTExYjdlYi9jYjllZWE5Zi0xNTZhLTQ1OWItODBiMS0wMDI2ZDM5ZWU5ZGYvNGUyMjQ2MzAtNTk5My00OTlhLTkxYjktNWUwY2JjMzQ1ZDM2IiwiaWF0IjoxNzA5NzcwNzM0LCJleHAiOjMzMjgwMzMwNzM0fQ.VPl-SMJtIhWIhkI96l9j6R9Rzmxzgv0ZmKskTcx1b9s "=298x")

**Comment by znation** [comment]
Partially addressed in referenced PR by putting extension next to "Unknown". Will also need to change the logic so we then combine multiple entries that have the same text.

**Comment by bnord007** [comment]
bnord007 will follow up with znation.
