### ISSUE TITLE
Using SSH instead of HTTP

### ISSUE THREAD

**Issue by habedi** [xetdata/xet-tools#37]
Hey,

I want to switch from HTTP to SSH when working with a repository. The repository has a URL like

`https://xethub.com/USERNAME/REPO_NAME`

but I'm not sure now, for instance, what the URL should be when I want to clone the same repository over SSH.

I tried

`git clone git@xethub.com:USERNAME/REPO_NAME.git`

and 

`git clone ssh+git@xethub.com:USERNAME/REPO_NAME.git`.

But these URLs are not working.

I also tried 

`ssh -T git@xethub.com`

assuming that XetHub might have a similar interface to GitHub and got 

`git@xethub.com: Permission denied (publickey).`

in response. (I already uploaded my key to XetHub.)

**Any suggestion on how to fix this problem?**

**Comment by ylow** [comment]
The ssh URL form is `xet@xethub.com:USERNAME/REPONAME.git`
