### ISSUE TITLE
Provide Statically Linked Binaries for xet-core (git-xet | xetcmd | xetmnt)

### ISSUE THREAD

**Issue by Azathothas** [xetdata/xet-tools#38]
The prebuilt binaries available at https://github.com/xetdata/xet-tools/releases are dynamically linked & won't work on most linux distros. See : [git-xet does not run on CentOS 7.9 #19 ](https://github.com/xetdata/xet-tools/issues/19)

Metadata for **`xet-linux-x86_64.tar.gz`** Released here:
```bash
!# Source
$ https://github.com/xetdata/xet-tools/releases/download/v0.13.0/xet-linux-x86_64.tar.gz
SHA256SUM: 25fffa7adf834586c76246dc97fede377c21f895a017fbdd514b5d7e3ccefec5

!# Dynamic Libs
$ file git-xet
git-xet: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=4efa73cd7f9e5ee2d922ad4282080e8e8d92f9c8, for GNU/Linux 2.6.32, stripped

$ ldd git-xet
        linux-vdso.so.1 (0x00007fffc1dad000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0ca7e00000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0caa45f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0caa43b000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0caa436000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0ca81fb000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0ca8114000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0ca810f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0ca7a00000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0caa48a000)
        
!# Size
$ du -sh git-xet
35M     git-xet
$ stat -c "%s bytes" git-xet
35840920 bytes

!# alpine-linux test
./git-xet : not found
File I/O error : No such file or directory (os error 2)
```

Metadata for [**`https://bin.ajam.dev/x86_64_Linux/git-xet`**](https://bin.ajam.dev/x86_64_Linux/git-xet)
> - Compiled using : https://github.com/Azathothas/Toolpacks/blob/main/.github/scripts/x86_64_Linux/bins/git-xet.sh
```bash
!# Source
$ https://bin.ajam.dev/x86_64_Linux/git-xet
SHA256SUM: b14bd751c5f54a165b4d3174547821ade706e448592779a1daeab0f8269fd86f 

!# Dynamic Libs
$ file git-xet
git-xet: git-xet: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, for GNU/Linux 3.2.0, stripped

$ ldd git-xet
        statically linked

!# Size
$ du -sh git-xet
33M     git-xet
$ stat -c "%s bytes" git-xet
34568376 bytes

!# alpine-linux test
./git-xet
git-xet 0.13.1-3767db3-dirty
```

As you can see, not only it's static, but more optimized & less in size.
I frequently have to spin up ephemeral containers on cloud, usually alpine, and the official binaries never work as alpine doesn't have the required dynamic libs.

**Comment by hoytak** [comment]
This is great work, @Azathothas.  I think it makes sense to me.  

For our build process, I think it would make sense to incorporate this into the emitted flags in our build.rs script that is used in compiling git-xet -- see https://github.com/xetdata/xet-core/blob/main/rust/gitxet/build.rs.  I'll work on doing that here, or if you felt like putting up a PR I will happily work with you to get it in.  

Thank you!
