### ISSUE TITLE
Submit git-xet-windows-installer.exe to Microsoft to eliminate Smart Screen warning

### ISSUE THREAD

**Issue by watmildon** [xetdata/xet-tools#39]
**Describe the bug**
The current installation experience runs into a small hurdle on Windows machines. Microsoft Defender uses various heuristics for things downloaded from the internet. You can submit your files so that users won't see a scary and confusing dialog when they run the installer.

https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/
https://microsoft.com/en-us/wdsi/filesubmission/

**Frequency**
On first install

**Steps to reproduce**
To reproduce the behavior:
1. Download the installer
2. Run the installer

**Expected behavior**
Get a more typical UAC prompt for software install that changes machine state

**Screenshots**
![image](https://github.com/xetdata/xet-tools/assets/118567155/c16fa09e-4d9b-4230-b21d-ed276a10c3a1)

**Environment**
 - Internet connection: all
 - Device: all
 - OS: Windows
 - Browser: n/a
 - CLI version: n/a

**Additional context**
As it stands, Windows users need to click the quite unintuitive "More Info" link then the a run button appears.

**Comment by erinys** [comment]
Thanks for the report! This is definitely a hassle for Windows users. We did submit the executable to Microsoft, but they need to be submitted for every release and the amount of time it takes to be approved is indeterminate so it doesn't always guarantee the removal of this warning. We have documented some of the issues in the detailed Windows [install instructions](https://xethub.com/assets/docs/getting-started/install).
