### ISSUE TITLE
Commit doesn't work from VS Code on Windows - "xet is not a git command"

### ISSUE THREAD

**Issue by watmildon** [xetdata/xet-tools#40]
**Describe the bug**
I have cloned a xet repo using the VSCode splash page "Clone git repository". After adding some files I tried to commit this to the local repo and got an error dialog "xet is not a git command". I am able to interact with the repo (add/commit/push) using the command line.

**Frequency**
Persistent

**Steps to reproduce**
To reproduce the behavior:
1. Create a xet repo on the website
2. Xet clone the website from the command line
3. Launch VSCode and open the folder
4. Add things, a readme, drop a big data file in there, have fun
5. Try to commit using VSCode
6. Error

**Expected behavior**
Commit files

**Screenshots**
![image](https://github.com/xetdata/xet-tools/assets/118567155/bb1e2320-0df4-430a-8118-8aadcf795c5d)
![image](https://github.com/xetdata/xet-tools/assets/118567155/c0a340d1-5f55-493d-a806-eaaf8dd4f2c7)

**Environment**
 - Internet connection: wired
 - Device: desktop
 - OS: Windows 10 22H2
 - Browser: n/a
 - CLI version: 0.13.0

**Additional context**
Relaunching VS Code does not resolve the issue.

**Comment by erinys** [comment]
Doesn't reproduce on Mac, likely Windows only issue. VSCode may have its own Git version for Windows.
