### ISSUE TITLE
Not managing large files

### ISSUE THREAD

**Issue by MiguelRodo** [xetdata/xet-tools#44]
**Describe the bug**
Pushes of files larger than 1MB are getting rejected because they're not being managed by xet. I thought that simply having `git-xet` installed and `.gitattributes` as follows in the root of the repo would force git-xet to manage it:

```sh
* filter=xet diff=xet merge=xet -text
*.gitattributes filter=
*.xet/** filter=
```

I've clearly misconfigured somewhere.

**Frequency**
Every time.

**Steps to reproduce**
Commit the file and try push it. I just used the standard Git commands (`git add`, `git commit`, `git push`) based on these docs: [https://xethub.com/assets/docs/large-repos/lazy-clone](https://xethub.com/assets/docs/large-repos/lazy-clone); [https://xethub.com/assets/docs/getting-started/hello](https://xethub.com/assets/docs/getting-started/hello).

**Expected behavior**
Upload to XetHub.

**Screenshots**

![image](https://uploads.linear.app/04f79090-88ee-4279-886c-d14ec911b7eb/d46abc27-a60e-4c39-8578-39c80d10f404/7fcb8e68-4275-4d3f-9157-135456cbc919?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA0Zjc5MDkwLTg4ZWUtNDI3OS04ODZjLWQxNGVjOTExYjdlYi9kNDZhYmMyNy1hNjBlLTRjMzktODU3OC0zOWM4MGQxMGY0MDQvN2ZjYjhlNjgtNDI3NS00ZDNmLTkxNTctMTM1NDU2Y2JjOTE5IiwiaWF0IjoxNzExMzkyMTA2LCJleHAiOjMzMjgxOTUyMTA2fQ.mXMQWG-mXIWISG1RKTLju4YOeu5FIDpfgw4FB7oOdhY)

**Environment**

* Internet connection: unsure, university internet on our HPC (at the University of Cape Town).
* Device: Linux server:
  * Architecture:            x86_64
  * CPU op-mode(s):        32-bit, 64-bit
  * Address sizes:         46 bits physical, 48 bits virtual
  * Byte Order:            Little Endian
* OS: CensOS 7
* Browser: N/A
* CLI version: 0.13.0

**Additional context**
I also had an upload of several tens of GBs take days and not complete. I then wrote a shell script to upload by batches of ten files, and then got this error when uploading this file. So the issue is that xet isn't managing things like I thought it would.

Oh, and I'm running these commands from within an apptainer container (with `singularity` as the container runtime).

Besides the project contents, here is the output from `ls -al`:

```sh
drwxr-xr-x  6 1796 1796  5 Mar 25 08:25 .
drwxrwxr-x 14 1796 1796 12 Mar 22 14:04 ..
drwxr-xr-x  9 1796 1796 16 Mar 25 10:56 .git
-rw-r--r--  1 1796 1796 79 Jan 17 11:13 .gitattributes
```

**Comment by hoytak** [comment]
Two likely issues here: either git-xet isn't available on your path when you are trying to run git, or the global filter config isn't set. 

1. To check if it's installed, try running `git xet --version`. This should show a relatively recent version (latest was 0.13.2).   If that works, then git-xet should be on your path.   If not, then the instructions for this are in https://xethub.com/assets/docs/getting-started/install. 

2. The filter config isn't set.  This is a global git config value that is set by running `git xet install` .  You should see this if it's configured properly:

```bash
$ git config --global --get-regexp 'filter.xet.*'
filter.xet.process git xet filter
filter.xet.required true
```

If this isn't the case, try running `git-xet install` to reinstall the filter config.   This is a very lightweight operation and can be run multiple times without a problem, so it's fine to include it as part of your automation script.  And if for some reason in your automated setup the global git config doesn't work, you can run `git-xet install --local` within the repository to set it up for just that copy of the repo, but this isn't recommended.

**Comment by MiguelRodo** [comment]
The second issue was it, and the solution fixed it. Thanks!
