### ISSUE TITLE
www.xetbeta.com doesn't resolve

### ISSUE THREAD

**Issue by erinys** [xetdata/xet-tools#6]
**Describe the bug**
Docs had a link to the XetHub UI as www.xetbeta.com, which results in a 404.

**Frequency**
Persistent

**Steps to reproduce**
To reproduce the behavior:
1. Go to www.xetbeta.com
2. Get error

**Expected behavior**
xetbeta.com works, I would expect www.xetbeta to as well. In the meantime, fix the link in the docs.

**Screenshots**
![image](https://user-images.githubusercontent.com/1296134/167706950-2c91ded3-3860-4a18-8768-25e509a399f0.png)

**Environment**
 - Internet connection: Home wireless
 - Device: MacBook Pro
 - OS: macOS 13.2
 - Browser: Safari
 - CLI version: N/A

**Additional context**
Reported via email.

**Comment by erinys** [comment]
Docs have been updated to point to xetbeta.com, still need to have www.xetbeta.com redirect!

**Comment by jgodlew** [comment]
This should work now: www.xethub.com (and www.xetbeta.com)
